#Familiarizing text editor,IDE,code analysis tools.
print("Student Details:")
print("Name of the student:")
a=input()
print("Address of the student:")
b=input()
print("Qualification:")
c=input()
print("Phone Number:")
d=input()
print(a)
print(b)
print(c)
print(d)
